import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { FormEvent, useState } from "react";
import { Building2, Loader2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/cadastro")({ component: CadastroPage });

function CadastroPage() {
  const navigate=useNavigate(); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [condo,setCondo]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [ok,setOk]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const {data,error:a}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{full_name:name.trim()}}});if(a)throw a;if(data.session){const {data:d,error:r}=await (supabase as any).rpc("create_condominio",{p_nome:condo.trim(),p_quantidade_unidades:0});if(r)throw r;await navigate({to:"/dashboard"});}else setOk("Conta criada. Confirme o e-mail para concluir o acesso.");}catch(err){setError(err instanceof Error?err.message:"Não foi possível criar a conta.");}finally{setBusy(false);}}
  return <main className="min-h-screen bg-slate-50 flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-lg rounded-3xl border bg-white p-8 shadow-sm"><Link to="/" className="flex items-center gap-3 font-bold"><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-900 text-white"><Building2 className="h-5 w-5"/></span>SindCoop</Link><h1 className="mt-8 text-2xl font-bold">Comece seu condomínio</h1><p className="mt-1 text-sm text-slate-500">Crie sua conta e inicie o período de teste.</p><div className="mt-6 grid gap-4"><label className="grid gap-2 text-sm font-medium">Nome<input required value={name} onChange={e=>setName(e.target.value)} className="rounded-xl border px-3 py-3"/></label><label className="grid gap-2 text-sm font-medium">E-mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="rounded-xl border px-3 py-3"/></label><label className="grid gap-2 text-sm font-medium">Senha<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="rounded-xl border px-3 py-3"/></label><label className="grid gap-2 text-sm font-medium">Nome do condomínio<input required value={condo} onChange={e=>setCondo(e.target.value)} className="rounded-xl border px-3 py-3"/></label></div>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{ok&&<div className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{ok}</div>}<button disabled={busy} className="mt-6 flex w-full justify-center gap-2 rounded-xl bg-slate-950 px-4 py-3 font-semibold text-white disabled:opacity-60">{busy&&<Loader2 className="h-4 w-4 animate-spin"/>}Criar conta</button><p className="mt-5 text-center text-sm text-slate-500">Já possui conta? <Link to="/login" className="font-semibold text-slate-900">Entrar</Link></p></form></main>;
}
