import { createFileRoute } from "@tanstack/react-router";
import { LegalPage } from "@/components/legal-page";

export const Route = createFileRoute("/politica-de-privacidade")({
  head: () => ({ meta: [{ title: "Política de Privacidade | SindCoop" }, { name: "description", content: "Como o SindCoop trata e protege dados pessoais no contexto da gestão condominial." }] }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return <LegalPage title="Política de Privacidade" subtitle="Entenda quais dados podem ser tratados, por que são utilizados e quais direitos você pode exercer." icon="privacy">
    <section><h2>1. Objetivo e abrangência</h2><p>Esta Política explica, em linguagem acessível, como dados pessoais podem ser tratados durante o cadastro, autenticação e utilização do SindCoop. Aplica-se aos usuários da Plataforma e às informações de moradores, visitantes, funcionários, prestadores e outras pessoas que sejam cadastradas por um condomínio.</p><p>O tratamento efetivo depende dos módulos utilizados, das configurações da conta e das instruções do condomínio responsável pelos dados. O administrador do condomínio deve informar às pessoas afetadas sobre os tratamentos que realiza por meio da Plataforma.</p></section>
    <section><h2>2. Quais dados podem ser tratados</h2><ul><li><strong>Dados de conta:</strong> nome, e-mail, identificadores da conta, credenciais protegidas e informações de autenticação.</li><li><strong>Dados do condomínio:</strong> nome, CNPJ, endereço, contatos, logotipo, unidades e informações administrativas.</li><li><strong>Dados de moradores e usuários:</strong> nome, unidade, vínculo, contato e, quando informado e necessário, documentos de identificação.</li><li><strong>Dados operacionais:</strong> registros de portaria, visitantes, veículos, entregas, reservas, ocorrências, avisos, documentos e movimentações financeiras cadastradas.</li><li><strong>Dados técnicos e de segurança:</strong> informações de sessão, registros de acesso, data e hora de operações, eventos de auditoria e informações técnicas necessárias para proteger e manter o serviço.</li></ul><p>Não informe dados pessoais sensíveis ou documentos excessivos sem necessidade, autorização e fundamento legal adequados.</p></section>
    <section><h2>3. Finalidades do tratamento</h2><p>Os dados podem ser utilizados para criar e administrar contas; autenticar usuários; associar usuários ao condomínio correto; disponibilizar os módulos contratados; manter cadastros e registros operacionais; apoiar a segurança física e digital; atender solicitações; prevenir fraudes e acessos indevidos; diagnosticar falhas; cumprir obrigações legais; e exercer direitos em procedimentos administrativos ou judiciais.</p></section>
    <section><h2>4. Bases legais e papéis de cada responsável</h2><p>A LGPD exige uma base legal adequada para cada operação de tratamento. Conforme o contexto, podem ser aplicáveis execução de contrato ou procedimentos preliminares, cumprimento de obrigação legal ou regulatória, exercício regular de direitos, legítimo interesse após avaliação pertinente ou consentimento válido, quando necessário.</p><p>Em muitos usos cotidianos, o condomínio ou a administradora define por que e como os dados de moradores, visitantes e funcionários são tratados e poderá atuar como controlador. O fornecedor da Plataforma poderá atuar como operador ao tratar esses dados sob instruções, e como controlador independente para tratamentos próprios, como gestão de contas e segurança do serviço, quando aplicável. Os papéis concretos devem ser definidos de acordo com as operações reais e os contratos.</p></section>
    <section><h2>5. Compartilhamento de dados</h2><p>Os dados podem ser acessados por usuários autorizados do mesmo condomínio conforme suas permissões e compartilhados, na medida necessária, com fornecedores de hospedagem, banco de dados, autenticação, armazenamento, suporte e segurança; com autoridades públicas quando houver obrigação legal ou ordem válida; ou com terceiros quando houver base legal e necessidade para proteger direitos e prevenir fraude.</p><p>Não se deve presumir que todos os dados sejam visíveis a todos os usuários. O acesso deve respeitar as permissões do sistema e as regras aplicáveis. O responsável pela implantação deve verificar as configurações, políticas de acesso e contratos com fornecedores antes de utilizar dados reais.</p></section>
    <section><h2>6. Armazenamento e transferência internacional</h2><p>Dados são mantidos pelo período necessário para cumprir as finalidades informadas, atender obrigações legais, resolver disputas, manter registros de segurança e executar contratos. Prazos específicos dependem do tipo de registro e das obrigações aplicáveis. Ao fim da necessidade, os dados devem ser eliminados ou anonimizados, ressalvadas hipóteses legais de conservação.</p><p>Dependendo da configuração de hospedagem e dos fornecedores utilizados, dados ou cópias de segurança poderão ser processados em outros países. Quando houver transferência internacional, ela deverá ocorrer de acordo com os requisitos e mecanismos previstos na LGPD e na regulamentação aplicável.</p></section>
    <section><h2>7. Segurança da informação</h2><p>São recomendadas e, conforme a implementação, utilizadas medidas como autenticação, controle de permissões, isolamento de dados por condomínio, comunicações protegidas, registros de auditoria e restrição de acesso administrativo. Nenhuma solução é capaz de garantir segurança absoluta. Usuários devem manter senhas seguras, encerrar sessões em dispositivos compartilhados e comunicar suspeitas de incidentes.</p><p>A administração responsável deve manter políticas de acesso e cópias de segurança adequadas, revisar permissões periodicamente e tratar incidentes de acordo com as obrigações legais e regulamentares.</p></section>
    <section><h2>8. Cookies e tecnologias semelhantes</h2><p>A Plataforma pode utilizar armazenamento técnico, identificadores de sessão e tecnologias estritamente necessárias para autenticação, segurança e funcionamento da aplicação. Se forem adicionadas ferramentas de análise, publicidade ou tecnologias não essenciais, sua finalidade, base legal e eventual mecanismo de escolha deverão ser informados de forma específica.</p></section>
    <section><h2>9. Direitos dos titulares</h2><p>Nos termos da LGPD e observadas as condições legais, a pessoa titular pode solicitar confirmação da existência de tratamento, acesso, correção de dados incompletos ou inexatos, anonimização, bloqueio ou eliminação quando cabível, portabilidade quando regulamentada e aplicável, informações sobre compartilhamento, revisão de decisões automatizadas quando pertinente, e revogação do consentimento quando esse for a base legal.</p><p>Para dados administrados pelo condomínio, encaminhe o pedido ao síndico, à administradora ou ao canal de privacidade indicado pelo condomínio. Para dados tratados diretamente pelo operador da Plataforma, utilize o canal oficial de privacidade que deverá ser divulgado pelo responsável legal pelo SindCoop. Poderá ser necessário confirmar a identidade do solicitante para proteger os dados de terceiros.</p></section>
    <section><h2>10. Crianças e adolescentes</h2><p>A Plataforma não é destinada a que crianças criem contas de forma independente. Quando dados de crianças ou adolescentes forem tratados em rotinas condominiais, o responsável pelo tratamento deverá observar o melhor interesse e os requisitos específicos da legislação, adotando salvaguardas apropriadas.</p></section>
    <section><h2>11. Atualizações desta política</h2><p>Esta Política poderá ser atualizada para refletir mudanças no serviço, nos fornecedores, nas práticas de tratamento ou na legislação. A versão vigente ficará disponível nesta página, com a data de atualização. Mudanças relevantes devem ser comunicadas por meios apropriados, quando necessário.</p></section>
    <section><h2>12. Contato e autoridade competente</h2><p>Dúvidas e solicitações relacionadas a dados pessoais devem ser direcionadas ao controlador responsável pelo tratamento ou ao canal de privacidade que ele disponibilizar. A identificação jurídica do operador da Plataforma e o endereço de contato oficial precisam ser informados antes da disponibilização pública do serviço. A pessoa titular também pode apresentar petição à Autoridade Nacional de Proteção de Dados (ANPD), conforme os procedimentos aplicáveis.</p></section>
  </LegalPage>;
}
