import { createFileRoute } from "@tanstack/react-router";
import { LegalPage } from "@/components/legal-page";

export const Route = createFileRoute("/termos-de-uso")({
  head: () => ({ meta: [{ title: "Termos de Uso | SindCoop" }, { name: "description", content: "Condições de acesso e utilização da plataforma SindCoop." }] }),
  component: TermsPage,
});

function TermsPage() {
  return <LegalPage title="Termos de Uso" subtitle="Leia as condições para acessar e utilizar os recursos de gestão condominial do SindCoop." icon="terms">
    <section><h2>1. Aceitação destes termos</h2><p>Estes Termos de Uso regulam o acesso e a utilização da plataforma SindCoop (“Plataforma”), destinada a apoiar rotinas administrativas e operacionais de condomínios. Ao criar uma conta, acessar ou utilizar a Plataforma, o usuário declara que leu e compreendeu estes termos. Se não concordar, não deverá utilizar os serviços.</p></section>
    <section><h2>2. O que é o SindCoop</h2><p>O SindCoop disponibiliza ferramentas digitais para organização de dados condominiais, unidades, moradores, funcionários, veículos, avisos, ocorrências, reservas, portaria, entregas, documentos, informações financeiras e relatórios, conforme os módulos habilitados e as permissões atribuídas. A disponibilidade de cada recurso pode variar conforme configuração, perfil de acesso e estágio de implantação.</p></section>
    <section><h2>3. Cadastro e segurança da conta</h2><ul><li>Forneça informações corretas, atuais e autorizadas para uso.</li><li>Mantenha suas credenciais em sigilo e não compartilhe sua conta com terceiros.</li><li>Avise o responsável pela administração da Plataforma caso suspeite de acesso não autorizado.</li><li>Utilize somente os dados e módulos compatíveis com sua função e autorização no condomínio.</li><li>O responsável por cada condomínio deve revisar os acessos de seus usuários e removê-los quando deixarem de ser necessários.</li></ul><p>O usuário é responsável pelas atividades realizadas com sua conta, exceto quando demonstrado que o uso indevido decorreu de falha atribuível ao serviço ou de outra causa legalmente aplicável.</p></section>
    <section><h2>4. Uso permitido e responsabilidades</h2><p>A Plataforma deve ser utilizada para finalidades legítimas relacionadas à administração condominial e em conformidade com a legislação, a convenção e o regulamento do condomínio. É proibido:</p><ul><li>acessar dados, contas, áreas ou condomínios sem autorização;</li><li>inserir conteúdo ilícito, fraudulento, discriminatório, ameaçador ou que viole direitos de terceiros;</li><li>tentar contornar controles de acesso, comprometer a segurança ou interferir na disponibilidade do serviço;</li><li>usar dados pessoais para publicidade, perseguição ou finalidade incompatível com a finalidade informada;</li><li>copiar, revender ou explorar a Plataforma fora das permissões concedidas.</li></ul></section>
    <section><h2>5. Dados inseridos pelos usuários</h2><p>O usuário e a administração do condomínio devem possuir base legal e autorização apropriadas para cadastrar ou compartilhar informações, imagens, documentos e dados pessoais. Devem limitar o conteúdo ao necessário, manter os dados corretos e evitar inserir informações sensíveis quando não houver necessidade e fundamento legal. O condomínio continua responsável pelas decisões administrativas e pela legitimidade dos dados que fornece.</p></section>
    <section><h2>6. Privacidade e proteção de dados</h2><p>O tratamento de dados pessoais relacionado ao uso da Plataforma é descrito na <a href="/politica-de-privacidade">Política de Privacidade</a>, que deve ser lida em conjunto com estes termos. O tratamento observará a legislação aplicável, inclusive a Lei nº 13.709/2018 (LGPD), conforme os papéis e as responsabilidades de cada agente de tratamento.</p></section>
    <section><h2>7. Disponibilidade, manutenção e alterações</h2><p>Empregamos esforços razoáveis para manter a Plataforma disponível e segura, mas não garantimos operação ininterrupta, ausência absoluta de falhas ou compatibilidade permanente com todo dispositivo. Poderão ocorrer interrupções para manutenção, atualizações, falhas de fornecedores ou eventos fora do controle razoável. Recursos, interfaces e estes termos podem ser atualizados; mudanças relevantes devem ser comunicadas por meios apropriados.</p></section>
    <section><h2>8. Serviços de terceiros</h2><p>A Plataforma pode depender de provedores de infraestrutura, autenticação, armazenamento, hospedagem, comunicação ou outros serviços externos. Esses serviços possuem condições próprias e podem sofrer indisponibilidades. O uso de fornecedores não elimina as responsabilidades que a legislação atribui ao operador da Plataforma ou ao condomínio.</p></section>
    <section><h2>9. Propriedade intelectual</h2><p>Salvo indicação em contrário, a identidade visual, o desenho, os textos, os componentes e os demais elementos da Plataforma são protegidos por direitos de propriedade intelectual. Estes termos concedem uma autorização limitada, revogável e não exclusiva para utilizar o serviço conforme sua finalidade, sem transferir direitos de propriedade ao usuário. Os dados e arquivos legítimos inseridos pelo usuário não passam a pertencer ao SindCoop apenas por serem armazenados na Plataforma.</p></section>
    <section><h2>10. Suspensão e encerramento</h2><p>O acesso poderá ser suspenso ou limitado quando necessário para proteger contas, dados, usuários, a segurança da Plataforma ou para apurar suspeita de uso ilícito ou violação destes termos, respeitadas as exigências legais e, quando viável, a comunicação ao responsável. O encerramento de conta ou contrato deverá ser solicitado ao administrador responsável, observadas as regras de retenção e as obrigações legais aplicáveis.</p></section>
    <section><h2>11. Limites de responsabilidade</h2><p>O SindCoop é uma ferramenta de apoio e não substitui a atuação de síndicos, administradoras, contadores, advogados, profissionais de segurança ou outros especialistas. A administração do condomínio deve conferir lançamentos, documentos, relatórios e decisões antes de utilizá-los para fins oficiais. Nenhuma disposição destes termos exclui direitos ou responsabilidades que não possam ser afastados pela legislação.</p></section>
    <section><h2>12. Legislação e contato</h2><p>Estes termos são interpretados conforme as leis brasileiras, sem prejuízo das normas obrigatórias aplicáveis. Dúvidas, solicitações ou reclamações devem ser encaminhadas ao canal oficial informado pelo responsável legal pela operação do SindCoop e/ou pelo administrador do condomínio. Os dados de identificação e contato do operador devem estar disponíveis antes da oferta pública do serviço.</p></section>
  </LegalPage>;
}
